[package]
name = "broken-links"
version = "0.1.0"
authors = ["Parth <parth@mehrotra.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
http = "0.1.18"
reqwest = "0.9.21"